org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version=0.0.4
maven_group=io.github.tr100000

# Dependencies
# https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

fabric_api_version=0.155.2+26.2
modmenu_version=20.0.1
yacl_version=3.9.6+26.2
codec2schema_version=0.3.6+26.2

# Publishing
modrinth_extra_minecraft_versions=
